[project]
name = "aho-corasick-py"
version = "0.1.0"
description = "A Python implementation of the Aho-Corasick string matching algorithm."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.ruff]
line-length = 120
